baseURL = "http://example.org/"
languageCode = "en-us"
title = "Website Title"
theme = "bulma-base"

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    title = "Title English"
    description = "A short description"
    weight = 1

    [language.en.newsletter]
      title = "Subscribe"

  [languages.de]
    languageName = "Deutsch"
    title = "Titel Deutsch"
    description = "Kurzbeschreibung"
    weight = 2


[params.logo]
    mobile = "/img/logo.svg"
    standard  = "/img/logo.svg"
    notext = "/img/logo.svg"
